name: E2E Test Pipeline

on:
  workflow_dispatch:
    inputs:
      ChannelId:
        description: 'Enter the sales channel to use :'
        required: true
        default: 'STG_AT'
      BrowserName:
        description: 'Enter the browser to use :'
        default: 'chrome'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
